CREATE TABLE IF NOT EXISTS media (
	id VARCHAR(32) NOT NULL PRIMARY KEY,
	mimetype VARCHAR(64) NOT NULL,
	upload_time TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "user" (
	id VARCHAR(32) PRIMARY KEY,
	username VARCHAR(32) CONSTRAINT unique_username UNIQUE,
	password VARCHAR(64) NOT NULL,
	profile_pic VARCHAR(32) NOT NULL REFERENCES media(id) ON DELETE RESTRICT,
	firstname VARCHAR(32) NOT NULL,
	lastname VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS todo_item (
	id VARCHAR(64) PRIMARY KEY,
	owner VARCHAR(32) NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
	creation_time TIMESTAMP NOT NULL DEFAULT now(),
	label VARCHAR(32) NOT NULL,
	description VARCHAR(384) DEFAULT NULL
);

